// hash: #3e9e798d
// @formatter:off

package me.wietlol.bitblock.codegenerator.data.models

import me.wietlol.bitblock.api.serialization.BitSerializable
import me.wietlol.utils.common.Jsonable

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:WTcTph
// @tomplot:customCode:end
// @formatter:off

sealed interface BitLiteralExpression : BitSerializable, BitExpression, Jsonable
{
	val value: Any
	
	override fun duplicate(): BitLiteralExpression
	
	// @formatter:on
	// @tomplot:customCode:start:0MOZ71
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
